Revert to serde-transcode approach to connecting serde pipelines
    Revert "wip: unifying types on match"
    Revert "Error: match arms have incompatible types"
    Revert "Introduce convert_to_format architecture"
    Revert "wip: initial bioserde demo"